version: '3.8'

services:
    # These are the configurations for our Node app
    # When Docker Compose starts this container it will automatically
    # use the Dockerfile in the directory to configure it
    app:
        image: node:16-alpine
        working_dir: /usr/app
        volumes:
            - ./:/usr/app
        ports:
            - 3001:3001
            - 9229:9229
        command: sh -c "sleep 3 && yarn dev"
